(function(){
var s=document.createElement('script');
s.type='application/ld+json';
s.textContent=JSON.stringify({"@context":"https://schema.org","@graph":[
{"@type":"Organization","@id":"https://www.cognifit.com/#organization","name":"CogniFit","url":"https://www.cognifit.com","logo":{"@type":"ImageObject","url":"https://cdn.jsdelivr.net/gh/joolomee/cognifit_longevity@main/logo.png"},"foundingDate":"1999","description":"Líder mundial em avaliações cognitivas digitais e treino cerebral personalizado baseado em IA.","sameAs":["https://www.facebook.com/CogniFit","https://twitter.com/CogniFit","https://www.linkedin.com/company/cognifit","https://www.youtube.com/user/CogniFit","https://www.instagram.com/cognifit"],"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.8","ratingCount":"6249358","bestRating":"5"}},
{"@type":["WebPage","MedicalWebPage"],"url":"https://cognifit-df2ae7.webflow.io/longevity","name":"CogniFit — Viva Mais. Pense Melhor. Mantenha a Sua Independência","inLanguage":"pt-PT","description":"Sistema científico de Longevidade Cerebral com treino cognitivo personalizado, validado em +1083 estudos clínicos.","datePublished":"2025-01-01","dateModified":"2026-04-15","specialty":{"@type":"MedicalSpecialty","name":"Neuropsychology"},"audience":{"@type":"PeopleAudience","suggestedMinAge":35},"about":{"@type":"MedicalCondition","name":"Declínio Cognitivo"},"lastReviewed":"2026-04-15","reviewedBy":{"@type":"Organization","name":"CogniFit Scientific Advisory Board"}},
{"@type":"WebApplication","name":"CogniFit Brain Training","applicationCategory":"HealthApplication","operatingSystem":"Web, iOS, Android","offers":{"@type":"Offer","price":"0","priceCurrency":"USD"},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.8","ratingCount":"6249358","bestRating":"5"}},
{"@type":"FAQPage","mainEntity":[{"@type":"Question","name":"O que é longevidade cerebral?","acceptedAnswer":{"@type":"Answer","text":"Longevidade cerebral significa manter a memória, o foco, o raciocínio e a tomada de decisões afiados o máximo de tempo possível à medida que envelhece."}},{"@type":"Question","name":"O treino cerebral funciona mesmo?","acceptedAnswer":{"@type":"Answer","text":"Sim. O estudo ACTIVE demonstrou que os benefícios duram até 10 anos. O CogniFit foi utilizado em +1.083 estudos clínicos."}},{"@type":"Question","name":"O que torna o CogniFit diferente?","acceptedAnswer":{"@type":"Answer","text":"Criado por neurocientistas em 1999, utilizado em 1.083+ estudos clínicos, e confiado por 3.530+ profissionais. Tecnologia adaptativa patenteada."}},{"@type":"Question","name":"Em quanto tempo noto a diferença?","acceptedAnswer":{"@type":"Answer","text":"A maioria sente-se mais afiada em 2-4 semanas. Estudos mostram melhorias mensuráveis às 8 semanas."}}]},
{"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"CogniFit","item":"https://www.cognifit.com"},{"@type":"ListItem","position":2,"name":"Longevidade Cerebral","item":"https://cognifit-df2ae7.webflow.io/longevity"}]},
{"@type":"Product","name":"CogniFit Brain Longevity System","description":"Sistema de treino cognitivo e avaliações cerebrais validadas cientificamente para longevidade cerebral.","brand":{"@type":"Brand","name":"CogniFit"},"aggregateRating":{"@type":"AggregateRating","ratingValue":"4.8","reviewCount":"6249358","bestRating":"5","worstRating":"1"},"offers":{"@type":"Offer","url":"https://www.cognifit.com/assessments","priceCurrency":"EUR","price":"0","availability":"https://schema.org/InStock"}}
]});
document.head.appendChild(s);
})();
